name: documentation

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
                
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.x
      # - run: pip install mkdocs-material mkdocs-jupyter
      # - run: mkdocs gh-deploy --force

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          miniconda-version: "latest"
          activate-environment: mkdocs
          environment-file: .github/environment.yml
#       - run: conda install mkdocs=1.3.0 mkdocs-material=8.4.1 mkdocs-material-extensions==1.0.3 mkdocs-jupyter=0.21.0 mkdocs-exclude -c conda-forge
      
      - name: mkdocs
        shell: bash -el {0}
        run: mkdocs gh-deploy --force